import type { PageStatus } from "@/db/types";
export const mockUsers = [
	{
		id: "mockUserId1",
		handle: "mockUserId1",
		profile: "mockUserId1",
		twitterHandle: "mockUserId1",
		createdAt: new Date(),
		updatedAt: new Date(),
		totalPoints: 0,
		isAi: false,
		name: "mockUserId1",
		image: "/test-user.png",
		plan: "free",
		hasGeminiApiKey: false,
	},
	{
		id: "mockUserId2",
		handle: "mockUserId2",
		profile: "mockUserId2",
		twitterHandle: "mockUserId2",
		createdAt: new Date(),
		updatedAt: new Date(),
		totalPoints: 0,
		isAi: false,
		name: "mockUserId2",
		image: "mockUserId2",
		plan: "free",
		hasGeminiApiKey: false,
	},
];

export const mockPages = [
	{
		id: 1,
		userId: "mockUserId1",
		content: "test",
		mdastJson: {},
		slug: "mockUserId1-page1",
		sourceLocale: "en",
		status: "PUBLIC" as PageStatus,
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		id: 2,
		userId: "mockUserId2",
		content: "test",
		mdastJson: {},
		slug: "mockUserId2-page1",
		sourceLocale: "en",
		status: "PUBLIC" as PageStatus,
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		id: 3,
		userId: "mockUserId1",
		content: "test",
		mdastJson: {},
		slug: "mockUserId1-page2-draft",
		sourceLocale: "en",
		status: "DRAFT" as PageStatus,
		createdAt: new Date(),
		updatedAt: new Date(),
	},
];
