/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Contentkind = "PAGE" | "PAGE_COMMENT";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Notificationtype = "FOLLOW" | "PAGE_COMMENT" | "PAGE_COMMENT_SEGMENT_TRANSLATION_VOTE" | "PAGE_LIKE" | "PAGE_SEGMENT_TRANSLATION_VOTE";

export type Pagestatus = "ARCHIVE" | "DRAFT" | "PUBLIC";

export type Segmenttypekey = "COMMENTARY" | "PRIMARY";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type Translationproofstatus = "HUMAN_TOUCHED" | "MACHINE_DRAFT" | "PROOFREAD" | "VALIDATED";

export type Translationstatus = "COMPLETED" | "FAILED" | "IN_PROGRESS" | "PENDING";

export interface _PrismaMigrations {
  applied_steps_count: Generated<number>;
  checksum: string;
  finished_at: Timestamp | null;
  id: string;
  logs: string | null;
  migration_name: string;
  rolled_back_at: Timestamp | null;
  started_at: Generated<Timestamp>;
}

export interface Accounts {
  access_token: string | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp | null;
  id: Generated<string>;
  id_token: string | null;
  password: string | null;
  provider: string;
  providerAccountId: string;
  refresh_token: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updated_at: Generated<Timestamp>;
  userId: string;
}

export interface Contents {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  import_file_id: number | null;
  kind: Contentkind;
  updated_at: Generated<Timestamp>;
}

export interface Follows {
  created_at: Generated<Timestamp>;
  follower_id: string;
  following_id: string;
  id: Generated<number>;
}

export interface GeminiApiKeys {
  api_key: Generated<string>;
  id: Generated<number>;
  user_id: string;
}

export interface ImportFiles {
  checksum: string;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  import_run_id: number;
  message: Generated<string>;
  path: string;
  status: Generated<string>;
}

export interface ImportRuns {
  finished_at: Timestamp | null;
  id: Generated<number>;
  started_at: Generated<Timestamp>;
  status: Generated<string>;
}

export interface LikePages {
  created_at: Generated<Timestamp>;
  guest_id: string | null;
  id: Generated<number>;
  page_id: number;
  user_id: string | null;
}

export interface NeonControlPlaneEndpoints {
  allowed_ips: string | null;
  endpoint_id: string;
}

export interface Notifications {
  actor_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  page_comment_id: number | null;
  page_id: number | null;
  read: Generated<boolean>;
  segment_translation_id: number | null;
  type: Notificationtype;
  user_id: string;
}

export interface PageComments {
  created_at: Generated<Timestamp>;
  id: number;
  is_deleted: Generated<boolean>;
  last_reply_at: Timestamp | null;
  locale: string;
  mdast_json: Json;
  page_id: number;
  parent_id: number | null;
  reply_count: Generated<number>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface PageLocaleTranslationProofs {
  id: Generated<number>;
  locale: string;
  page_id: number;
  translation_proof_status: Generated<Translationproofstatus>;
}

export interface Pages {
  created_at: Generated<Timestamp>;
  id: number;
  mdast_json: Json;
  order: Generated<number>;
  parent_id: number | null;
  slug: string;
  source_locale: Generated<string>;
  status: Generated<Pagestatus>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface PageViews {
  count: Generated<number>;
  pageId: number;
}

export interface SegmentAnnotationLinks {
  annotation_segment_id: number;
  created_at: Generated<Timestamp>;
  main_segment_id: number;
}

export interface SegmentMetadata {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  metadata_type_id: number;
  segment_id: number;
  value: string;
}

export interface SegmentMetadataTypes {
  id: Generated<number>;
  key: string;
  label: string;
}

export interface Segments {
  content_id: number;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  number: number;
  segment_type_id: number;
  text: string;
  text_and_occurrence_hash: string;
}

export interface SegmentTranslations {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  locale: string;
  point: Generated<number>;
  segment_id: number;
  text: string;
  user_id: string;
}

export interface SegmentTypes {
  id: Generated<number>;
  key: Segmenttypekey;
  label: string;
}

export interface Sessions {
  created_at: Generated<Timestamp>;
  expires: Timestamp;
  id: Generated<string>;
  ipAddress: string | null;
  sessionToken: string;
  updated_at: Generated<Timestamp>;
  userAgent: string | null;
  userId: string;
}

export interface TagPages {
  pageId: number;
  tagId: number;
}

export interface Tags {
  id: Generated<number>;
  name: string;
}

export interface TranslationJobs {
  aiModel: string;
  createdAt: Generated<Timestamp>;
  error: Generated<string>;
  id: Generated<number>;
  locale: string;
  pageId: number;
  progress: Generated<number>;
  status: Generated<Translationstatus>;
  updatedAt: Generated<Timestamp>;
  userId: string | null;
}

export interface TranslationVotes {
  created_at: Generated<Timestamp>;
  is_upvote: boolean;
  translation_id: number;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface UserCredentials {
  id: Generated<number>;
  password: string;
  user_id: string;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  emailVerified: boolean | null;
  handle: string;
  id: Generated<string>;
  image: Generated<string>;
  is_ai: Generated<boolean>;
  name: Generated<string>;
  plan: Generated<string>;
  profile: Generated<string>;
  provider: Generated<string>;
  total_points: Generated<number>;
  twitterHandle: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface UserSettings {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  target_locales: Generated<string[]>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Verifications {
  createdAt: Timestamp | null;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Timestamp | null;
  value: string;
}

export interface VerificationTokens {
  expires: Timestamp;
  identifier: string;
  token: string;
}

export interface DB {
  _prisma_migrations: _PrismaMigrations;
  accounts: Accounts;
  contents: Contents;
  follows: Follows;
  gemini_api_keys: GeminiApiKeys;
  import_files: ImportFiles;
  import_runs: ImportRuns;
  like_pages: LikePages;
  "neon_control_plane.endpoints": NeonControlPlaneEndpoints;
  notifications: Notifications;
  page_comments: PageComments;
  page_locale_translation_proofs: PageLocaleTranslationProofs;
  page_views: PageViews;
  pages: Pages;
  segment_annotation_links: SegmentAnnotationLinks;
  segment_metadata: SegmentMetadata;
  segment_metadata_types: SegmentMetadataTypes;
  segment_translations: SegmentTranslations;
  segment_types: SegmentTypes;
  segments: Segments;
  sessions: Sessions;
  tag_pages: TagPages;
  tags: Tags;
  translation_jobs: TranslationJobs;
  translation_votes: TranslationVotes;
  user_credentials: UserCredentials;
  user_settings: UserSettings;
  users: Users;
  verification_tokens: VerificationTokens;
  verifications: Verifications;
}
