databases:
  - name: evame-db
    plan: starter
    region: singapore

services:
- type: web
  name: evame
  runtime: node
  repo: https://github.com/ttizze/evame
  branch: main
  plan: starter
  region: singapore
  buildCommand: npm install && npm run build
  startCommand: npx prisma migrate deploy && npx prisma generate && npm start
  rootDir: web
  envVars:
    - key: DATABASE_URL
      fromDatabase:
        name: evame-db
        property: connectionString
    - key: REDIS_HOST
      fromService:
        type: redis
        name: evame-redis
        property: host
    - key: REDIS_PORT
      fromService:
        type: redis
        name: evame-redis
        property: port

- type: redis
  name: evame-redis
  plan: free
  region: singapore
  ipAllowList: []

