databases:
  - name: eveeve-db
    plan: starter
    region: singapore

services:
- type: web
  name: eveeve
  runtime: node
  repo: https://github.com/ttizze/eveeve
  branch: main
  plan: starter
  region: singapore
  buildCommand: bun run clear-queues && bun run install-and-build
  startCommand: bunx prisma migrate deploy && bunx prisma generate && bun run start
  rootDir: web
  envVars:
    - key: DATABASE_URL
      fromDatabase:
        name: eveeve-db
        property: connectionString
    - key: REDIS_HOST
      fromService:
        type: redis
        name: eveeve-redis
        property: host
    - key: REDIS_PORT
      fromService:
        type: redis
        name: eveeve-redis
        property: port

- type: redis
  name: eveeve-redis
  plan: free
  region: singapore
  ipAllowList: []
