databases:
  - name: remixdb
    plan: free
    region: singapore

services:
- type: web
  name: eveeve
  runtime: node
  repo: https://github.com/ttizze/eveeve
  branch: feature/render
  plan: free
  region: singapore
  buildCommand: bun run install-and-build
  startCommand: npx prisma migrate deploy && bun run start
  rootDir: web
  envVars:
    - key: DATABASE_URL
      fromDatabase:
        name: remixdb
        property: connectionString