# Exported from Render on 2024-07-13T13:22:37Z
databases:
- name: remixdb
  databaseName: remixdb_9yoe
  user: remixdb_9yoe_user
  plan: free
  region: oregon
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
version: "1"

# Exported from Render on 2024-07-13T13:20:50Z
services:
- type: web
  name: eveeve
  runtime: node
  repo: https://github.com/ttizze/eveeve
  branch: feature/render
  plan: free
  region: singapore
  buildCommand: bun run install-and-build
  startCommand: bun run start
  rootDir: web
version: "1"
