const copy = {
	en: {
		brand: "Digital Buddhism",
		title: "Read the Pāli canon",
		intro:
			"Read the Pāli source alongside translations in your chosen language and examine each passage at your own pace.",
		catalog:
			"Browse the published canon. Select a text to compare its source and translation candidates.",
		translationCount: (count: number) =>
			`${count} translation${count === 1 ? "" : "s"}`,
		read: "Read text",
		empty: "No published scriptures are available yet.",
		sectionLabel: "Pāli canon",
		source: "Pāli source",
		passage: "Passage",
		annotation: "Annotation",
		translations: "Translation candidates",
		translationDescription:
			"Compare published translations and vote for the one you find most faithful.",
		noTranslations: "No translation is published for this language yet.",
		mode: "View",
		both: "Source + translation",
		sourceOnly: "Source only",
		translationOnly: "Translation only",
		candidate: "Candidate",
		publicCandidate: "Published candidate",
		by: "by:",
		aiLabel: "AI translation",
		delete: "Delete",
		deleting: "Deleting…",
		otherTranslations: "Other translations",
		showAll: "Show all translations",
		collapse: "Show fewer translations",
		up: "Vote for this translation",
		down: "Downvote this translation",
		removeUp: "Remove vote",
		removeDown: "Remove downvote",
		saving: "Saving…",
		voteLogin: "Log in to vote.",
		voteError: "The vote could not be saved. Please try again later.",
		voteCount: (count: number) => `${count} vote${count === 1 ? "" : "s"}`,
		formHeadline: "Submit a translation",
		formDescription:
			"Review the source and share a translation in the selected language.",
		formLocale: "Translation language",
		formText: "Translation",
		formPlaceholder: "Write a translation",
		formHelp:
			"Aim for a clear translation that preserves the meaning of the source.",
		formSubmit: "Submit translation",
		formSubmitting: "Submitting…",
		formSuccess: "Translation submitted.",
		formEmpty: "Enter a translation.",
		formError:
			"The translation could not be submitted. Please try again later.",
		formLogin: "Log in to submit a translation.",
		jobTitle: "AI translation",
		jobDescription:
			"Start a job to translate this scripture into the selected language.",
		jobModel: "Translation model",
		jobStart: "Start AI translation",
		jobRetry: "Retry AI translation",
		jobStarting: "Starting…",
		jobProgress: "Progress",
		jobLogin: "Log in to use AI translation.",
		jobStatusError: "The AI translation status could not be loaded.",
		jobStartError:
			"AI translation could not be started. Please try again later.",
		status: {
			PENDING: "Pending",
			IN_PROGRESS: "In progress",
			COMPLETED: "Completed",
			FAILED: "Failed",
		},
		language: "Language",
		languageNavigation: "Display language",
		scriptureList: "Scripture list",
		scriptureHierarchy: "Scripture hierarchy",
		notFoundTitle: "Scripture not found",
		notFoundDescription:
			"The requested text is not available in this collection.",
		backToCollection: "Back to the collection",
	},
	ja: {
		brand: "デジタル仏教",
		title: "パーリ語仏典を読む",
		intro:
			"パーリ語の原文と、選択した言語の訳文を並べて読み、ことばの意味を静かに確かめられます。",
		catalog:
			"公開されている仏典を収録しています。題名を選ぶと、原文と翻訳候補を表示します。",
		translationCount: (count: number) => `翻訳 ${count}候補`,
		read: "読む",
		empty: "公開されている仏典はまだありません。",
		sectionLabel: "パーリ語仏典",
		source: "パーリ原文",
		passage: "本文",
		annotation: "注釈",
		translations: "翻訳候補",
		translationDescription:
			"公開されている訳を並べています。よりふさわしいと思う訳に投票できます。",
		noTranslations: "この言語の翻訳はまだ公開されていません。",
		mode: "表示モード",
		both: "原文と翻訳",
		sourceOnly: "原文のみ",
		translationOnly: "翻訳のみ",
		candidate: "訳",
		publicCandidate: "公開訳候補",
		by: "作成者:",
		aiLabel: "AI翻訳",
		delete: "削除",
		deleting: "削除中…",
		otherTranslations: "他の翻訳",
		showAll: "すべての翻訳を表示",
		collapse: "翻訳を折りたたむ",
		up: "この訳に投票",
		down: "この訳に反対票",
		removeUp: "投票を取り消す",
		removeDown: "反対票を取り消す",
		saving: "保存中…",
		voteLogin: "投票するにはログインが必要です。",
		voteError: "投票を保存できませんでした。時間をおいてお試しください。",
		voteCount: (count: number) => `${count}票`,
		formHeadline: "翻訳案を提出",
		formDescription: "原文を確認し、選択した言語の訳文を共有できます。",
		formLocale: "翻訳の言語",
		formText: "訳文",
		formPlaceholder: "訳文を入力",
		formHelp: "原文の意味を損なわない、読みやすい訳を心がけてください。",
		formSubmit: "翻訳案を提出",
		formSubmitting: "提出中…",
		formSuccess: "翻訳案を提出しました。",
		formEmpty: "訳文を入力してください。",
		formError: "翻訳案を提出できませんでした。時間をおいてお試しください。",
		formLogin: "翻訳案を提出するにはログインしてください。",
		jobTitle: "AI翻訳",
		jobDescription: "この仏典を選択中の言語へ翻訳するジョブを開始します。",
		jobModel: "AIモデル",
		jobStart: "AI翻訳を開始",
		jobRetry: "AI翻訳を再試行",
		jobStarting: "開始中…",
		jobProgress: "進捗",
		jobLogin: "AI翻訳を利用するにはログインしてください。",
		jobStatusError: "AI翻訳の状態を取得できませんでした。",
		jobStartError: "AI翻訳を開始できませんでした。時間をおいてお試しください。",
		status: {
			PENDING: "待機中",
			IN_PROGRESS: "処理中",
			COMPLETED: "完了",
			FAILED: "失敗",
		},
		language: "言語",
		languageNavigation: "表示言語",
		scriptureList: "仏典一覧",
		scriptureHierarchy: "仏典の階層",
		notFoundTitle: "仏典が見つかりません",
		notFoundDescription:
			"指定されたテキストはこのコレクションでは利用できません。",
		backToCollection: "コレクションに戻る",
	},
	es: {
		brand: "Digital Buddhism",
		title: "Leer el canon pāli",
		intro:
			"Lee el original pāli junto a las traducciones en el idioma que elijas y examina cada pasaje a tu ritmo.",
		catalog:
			"Explora el canon publicado. Selecciona un texto para comparar el original y las traducciones.",
		translationCount: (count: number) =>
			`${count} traducción${count === 1 ? "" : "es"}`,
		read: "Leer texto",
		empty: "Todavía no hay escrituras publicadas.",
		sectionLabel: "Canon pāli",
		source: "Original pāli",
		passage: "Pasaje",
		annotation: "Anotación",
		translations: "Traducciones candidatas",
		translationDescription:
			"Compara las traducciones publicadas y vota por la que te parezca más fiel.",
		noTranslations: "Todavía no hay una traducción publicada en este idioma.",
		mode: "Vista",
		both: "Original + traducción",
		sourceOnly: "Solo original",
		translationOnly: "Solo traducción",
		candidate: "Candidata",
		publicCandidate: "Candidata publicada",
		by: "por:",
		aiLabel: "Traducción de IA",
		delete: "Eliminar",
		deleting: "Eliminando…",
		otherTranslations: "Otras traducciones",
		showAll: "Mostrar todas las traducciones",
		collapse: "Mostrar menos traducciones",
		up: "Votar por esta traducción",
		down: "Votar en contra de esta traducción",
		removeUp: "Quitar voto",
		removeDown: "Quitar voto negativo",
		saving: "Guardando…",
		voteLogin: "Inicia sesión para votar.",
		voteError: "No se pudo guardar el voto. Inténtalo de nuevo más tarde.",
		voteCount: (count: number) => `${count} voto${count === 1 ? "" : "s"}`,
		formHeadline: "Enviar una traducción",
		formDescription:
			"Revisa el original y comparte una traducción en el idioma elegido.",
		formLocale: "Idioma de traducción",
		formText: "Traducción",
		formPlaceholder: "Escribe una traducción",
		formHelp:
			"Busca una traducción clara que conserve el sentido del original.",
		formSubmit: "Enviar traducción",
		formSubmitting: "Enviando…",
		formSuccess: "Traducción enviada.",
		formEmpty: "Escribe una traducción.",
		formError: "No se pudo enviar la traducción. Inténtalo de nuevo más tarde.",
		formLogin: "Inicia sesión para enviar una traducción.",
		jobTitle: "Traducción con IA",
		jobDescription:
			"Inicia un trabajo para traducir esta escritura al idioma elegido.",
		jobModel: "Modelo de traducción",
		jobStart: "Iniciar traducción con IA",
		jobRetry: "Reintentar traducción con IA",
		jobStarting: "Iniciando…",
		jobProgress: "Progreso",
		jobLogin: "Inicia sesión para usar la traducción con IA.",
		jobStatusError: "No se pudo cargar el estado de la traducción con IA.",
		jobStartError:
			"No se pudo iniciar la traducción con IA. Inténtalo de nuevo más tarde.",
		status: {
			PENDING: "Pendiente",
			IN_PROGRESS: "En curso",
			COMPLETED: "Completada",
			FAILED: "Fallida",
		},
		language: "Idioma",
		languageNavigation: "Idioma de visualización",
		scriptureList: "Lista de escrituras",
		scriptureHierarchy: "Jerarquía de la escritura",
		notFoundTitle: "Escritura no encontrada",
		notFoundDescription:
			"El texto solicitado no está disponible en esta colección.",
		backToCollection: "Volver a la colección",
	},
	ko: {
		brand: "Digital Buddhism",
		title: "팔리어 경전 읽기",
		intro:
			"선택한 언어의 번역과 팔리어 원문을 함께 읽으며 각 구절을 천천히 살펴보세요.",
		catalog:
			"공개된 경전을 둘러보세요. 원문과 번역 후보를 비교할 텍스트를 선택하세요.",
		translationCount: (count: number) => `${count}개 번역`,
		read: "텍스트 읽기",
		empty: "아직 공개된 경전이 없습니다.",
		sectionLabel: "팔리어 경전",
		source: "팔리어 원문",
		passage: "본문",
		annotation: "주석",
		translations: "번역 후보",
		translationDescription:
			"공개된 번역을 비교하고 가장 충실하다고 생각하는 번역에 투표하세요.",
		noTranslations: "이 언어로 공개된 번역이 아직 없습니다.",
		mode: "보기",
		both: "원문 + 번역",
		sourceOnly: "원문만",
		translationOnly: "번역만",
		candidate: "후보",
		publicCandidate: "공개 번역 후보",
		by: "작성자:",
		aiLabel: "AI 번역",
		delete: "삭제",
		deleting: "삭제 중…",
		otherTranslations: "다른 번역",
		showAll: "모든 번역 보기",
		collapse: "번역 접기",
		up: "이 번역에 투표",
		down: "이 번역에 반대 투표",
		removeUp: "투표 취소",
		removeDown: "반대 투표 취소",
		saving: "저장 중…",
		voteLogin: "투표하려면 로그인하세요.",
		voteError: "투표를 저장할 수 없습니다. 나중에 다시 시도하세요.",
		voteCount: (count: number) => `${count}표`,
		formHeadline: "번역 제출",
		formDescription: "원문을 확인하고 선택한 언어의 번역을 공유하세요.",
		formLocale: "번역 언어",
		formText: "번역",
		formPlaceholder: "번역을 입력하세요",
		formHelp: "원문의 의미를 보존하는 명확한 번역을 작성하세요.",
		formSubmit: "번역 제출",
		formSubmitting: "제출 중…",
		formSuccess: "번역이 제출되었습니다.",
		formEmpty: "번역을 입력하세요.",
		formError: "번역을 제출할 수 없습니다. 나중에 다시 시도하세요.",
		formLogin: "번역을 제출하려면 로그인하세요.",
		jobTitle: "AI 번역",
		jobDescription: "이 경전을 선택한 언어로 번역하는 작업을 시작합니다.",
		jobModel: "번역 모델",
		jobStart: "AI 번역 시작",
		jobRetry: "AI 번역 다시 시도",
		jobStarting: "시작 중…",
		jobProgress: "진행률",
		jobLogin: "AI 번역을 사용하려면 로그인하세요.",
		jobStatusError: "AI 번역 상태를 불러올 수 없습니다.",
		jobStartError: "AI 번역을 시작할 수 없습니다. 나중에 다시 시도하세요.",
		status: {
			PENDING: "대기 중",
			IN_PROGRESS: "진행 중",
			COMPLETED: "완료",
			FAILED: "실패",
		},
		language: "언어",
		languageNavigation: "표시 언어",
		scriptureList: "경전 목록",
		scriptureHierarchy: "경전 계층",
		notFoundTitle: "경전을 찾을 수 없습니다",
		notFoundDescription: "요청한 텍스트는 이 컬렉션에서 사용할 수 없습니다.",
		backToCollection: "컬렉션으로 돌아가기",
	},
	zh: {
		brand: "Digital Buddhism",
		title: "阅读巴利语经典",
		intro: "将巴利语原文与所选语言的译文并读，按自己的节奏理解每一段文字。",
		catalog: "浏览已发布的经典。选择文本以比较原文和译文候选。",
		translationCount: (count: number) => `${count} 条译文`,
		read: "阅读文本",
		empty: "暂时没有已发布的经典。",
		sectionLabel: "巴利语经典",
		source: "巴利语原文",
		passage: "段落",
		annotation: "注释",
		translations: "译文候选",
		translationDescription: "比较已发布的译文，并为你认为最忠实的译文投票。",
		noTranslations: "该语言尚未发布译文。",
		mode: "视图",
		both: "原文 + 译文",
		sourceOnly: "仅原文",
		translationOnly: "仅译文",
		candidate: "候选译文",
		publicCandidate: "已发布候选译文",
		by: "作者:",
		aiLabel: "AI 译文",
		delete: "删除",
		deleting: "删除中…",
		otherTranslations: "其他译文",
		showAll: "显示全部译文",
		collapse: "收起译文",
		up: "为此译文投票",
		down: "反对这条译文",
		removeUp: "取消投票",
		removeDown: "取消反对票",
		saving: "保存中…",
		voteLogin: "登录后即可投票。",
		voteError: "无法保存投票，请稍后再试。",
		voteCount: (count: number) => `${count} 票`,
		formHeadline: "提交译文",
		formDescription: "查看原文并分享所选语言的译文。",
		formLocale: "译文语言",
		formText: "译文",
		formPlaceholder: "输入译文",
		formHelp: "请在保留原文含义的同时，尽量清晰易读。",
		formSubmit: "提交译文",
		formSubmitting: "提交中…",
		formSuccess: "译文已提交。",
		formEmpty: "请输入译文。",
		formError: "无法提交译文，请稍后再试。",
		formLogin: "登录后即可提交译文。",
		jobTitle: "AI 翻译",
		jobDescription: "开始将这部经典翻译成所选语言。",
		jobModel: "翻译模型",
		jobStart: "开始 AI 翻译",
		jobRetry: "重试 AI 翻译",
		jobStarting: "开始中…",
		jobProgress: "进度",
		jobLogin: "登录后即可使用 AI 翻译。",
		jobStatusError: "无法加载 AI 翻译状态。",
		jobStartError: "无法开始 AI 翻译，请稍后再试。",
		status: {
			PENDING: "等待中",
			IN_PROGRESS: "进行中",
			COMPLETED: "已完成",
			FAILED: "失败",
		},
		language: "语言",
		languageNavigation: "显示语言",
		scriptureList: "经典列表",
		scriptureHierarchy: "经典层级",
		notFoundTitle: "未找到经典",
		notFoundDescription: "请求的文本在此经典集中不可用。",
		backToCollection: "返回经典列表",
	},
} as const;

export function getScriptureCopy(locale: string) {
	const code = locale.toLowerCase().split("-")[0];
	return copy[code as keyof typeof copy] ?? copy.en;
}
