/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Contentkind = "PAGE" | "PAGE_COMMENT";

export type Generated<T> =
	T extends ColumnType<infer S, infer I, infer U>
		? ColumnType<S, I | undefined, U>
		: ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<
	string,
	bigint | number | string,
	bigint | number | string
>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
	[x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Notificationtype =
	| "FOLLOW"
	| "PAGE_COMMENT"
	| "PAGE_COMMENT_SEGMENT_TRANSLATION_VOTE"
	| "PAGE_LIKE"
	| "PAGE_SEGMENT_TRANSLATION_VOTE";

export type Pagestatus = "ARCHIVE" | "DRAFT" | "PUBLIC";

export type Segmenttypekey = "COMMENTARY" | "PRIMARY";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type Translationproofstatus =
	| "HUMAN_TOUCHED"
	| "MACHINE_DRAFT"
	| "PROOFREAD"
	| "VALIDATED";

export type Translationstatus =
	| "COMPLETED"
	| "FAILED"
	| "IN_PROGRESS"
	| "PENDING";

export interface Accounts {
	accessToken: string | null;
	accessTokenExpiresAt: Timestamp | null;
	accountId: string;
	createdAt: Generated<Timestamp>;
	id: string;
	idToken: string | null;
	password: string | null;
	providerId: string;
	refreshToken: string | null;
	refreshTokenExpiresAt: Timestamp | null;
	scope: string | null;
	updatedAt: Generated<Timestamp>;
	userId: string;
}

export interface Contents {
	createdAt: Generated<Timestamp>;
	id: Generated<number>;
	importFileId: number | null;
	kind: Contentkind;
	updatedAt: Generated<Timestamp>;
}

export interface DrizzleDrizzleMigrations {
	createdAt: Int8 | null;
	hash: string;
	id: Generated<number>;
}

export interface Follows {
	createdAt: Generated<Timestamp>;
	followerId: string;
	followingId: string;
	id: Generated<number>;
}

export interface GeminiApiKeys {
	apiKey: Generated<string>;
	id: Generated<number>;
	userId: string;
}

export interface ImportFiles {
	checksum: string;
	createdAt: Generated<Timestamp>;
	id: Generated<number>;
	importRunId: number;
	message: Generated<string>;
	path: string;
	status: Generated<string>;
}

export interface ImportRuns {
	finishedAt: Timestamp | null;
	id: Generated<number>;
	startedAt: Generated<Timestamp>;
	status: Generated<string>;
}

export interface LikePages {
	createdAt: Generated<Timestamp>;
	id: Generated<number>;
	pageId: number;
	userId: string | null;
}

export interface NeonControlPlaneEndpoints {
	allowedIps: string | null;
	endpointId: string;
}

export interface Notifications {
	actorId: string;
	createdAt: Generated<Timestamp>;
	id: Generated<number>;
	pageCommentId: number | null;
	pageId: number | null;
	read: Generated<boolean>;
	segmentTranslationId: number | null;
	type: Notificationtype;
	userId: string;
}

export interface PageComments {
	createdAt: Generated<Timestamp>;
	id: number;
	isDeleted: Generated<boolean>;
	lastReplyAt: Timestamp | null;
	locale: string;
	mdastJson: Json;
	pageId: number;
	parentId: number | null;
	replyCount: Generated<number>;
	updatedAt: Generated<Timestamp>;
	userId: string;
}

export interface PageLocaleTranslationProofs {
	id: Generated<number>;
	locale: string;
	pageId: number;
	translationProofStatus: Generated<Translationproofstatus>;
}

export interface Pages {
	createdAt: Generated<Timestamp>;
	id: number;
	mdastJson: Json;
	order: Generated<number>;
	parentId: number | null;
	slug: string;
	sourceLocale: Generated<string>;
	status: Generated<Pagestatus>;
	updatedAt: Generated<Timestamp>;
	userId: string;
}

export interface PageViews {
	count: Generated<number>;
	pageId: number;
}

export interface SegmentAnnotationLinks {
	annotationSegmentId: number;
	createdAt: Generated<Timestamp>;
	mainSegmentId: number;
}

export interface SegmentMetadata {
	createdAt: Generated<Timestamp>;
	id: Generated<number>;
	metadataTypeId: number;
	segmentId: number;
	value: string;
}

export interface SegmentMetadataTypes {
	id: Generated<number>;
	key: string;
	label: string;
}

export interface Segments {
	contentId: number;
	createdAt: Generated<Timestamp>;
	id: Generated<number>;
	number: number;
	segmentTypeId: number;
	text: string;
	textAndOccurrenceHash: string;
}

export interface SegmentTranslations {
	createdAt: Generated<Timestamp>;
	id: Generated<number>;
	locale: string;
	point: Generated<number>;
	segmentId: number;
	text: string;
	userId: string;
}

export interface SegmentTypes {
	id: Generated<number>;
	key: Segmenttypekey;
	label: string;
}

export interface Sessions {
	createdAt: Generated<Timestamp>;
	expiresAt: Timestamp;
	id: string;
	ipAddress: string | null;
	token: string;
	updatedAt: Generated<Timestamp>;
	userAgent: string | null;
	userId: string;
}

export interface TagPages {
	pageId: number;
	tagId: number;
}

export interface Tags {
	id: Generated<number>;
	name: string;
}

export interface TranslationJobs {
	aiModel: string;
	createdAt: Generated<Timestamp>;
	error: Generated<string>;
	id: Generated<number>;
	locale: string;
	pageId: number;
	progress: Generated<number>;
	status: Generated<Translationstatus>;
	updatedAt: Generated<Timestamp>;
	userId: string | null;
}

export interface TranslationVotes {
	createdAt: Generated<Timestamp>;
	isUpvote: boolean;
	translationId: number;
	updatedAt: Generated<Timestamp>;
	userId: string;
}

export interface Users {
	createdAt: Generated<Timestamp>;
	email: string;
	emailVerified: boolean | null;
	handle: string;
	id: string;
	image: Generated<string>;
	isAi: Generated<boolean>;
	name: Generated<string>;
	plan: Generated<string>;
	profile: Generated<string>;
	provider: Generated<string>;
	totalPoints: Generated<number>;
	twitterHandle: Generated<string>;
	updatedAt: Generated<Timestamp>;
}

export interface UserSettings {
	createdAt: Generated<Timestamp>;
	id: Generated<number>;
	targetLocales: Generated<string[]>;
	updatedAt: Generated<Timestamp>;
	userId: string;
}

export interface Verifications {
	createdAt: Timestamp | null;
	expiresAt: Timestamp;
	id: string;
	identifier: string;
	updatedAt: Timestamp | null;
	value: string;
}

export interface DB {
	accounts: Accounts;
	contents: Contents;
	"drizzle.DrizzleMigrations": DrizzleDrizzleMigrations;
	follows: Follows;
	geminiApiKeys: GeminiApiKeys;
	importFiles: ImportFiles;
	importRuns: ImportRuns;
	likePages: LikePages;
	"neonControlPlane.endpoints": NeonControlPlaneEndpoints;
	notifications: Notifications;
	pageComments: PageComments;
	pageLocaleTranslationProofs: PageLocaleTranslationProofs;
	pages: Pages;
	pageViews: PageViews;
	segmentAnnotationLinks: SegmentAnnotationLinks;
	segmentMetadata: SegmentMetadata;
	segmentMetadataTypes: SegmentMetadataTypes;
	segments: Segments;
	segmentTranslations: SegmentTranslations;
	segmentTypes: SegmentTypes;
	sessions: Sessions;
	tagPages: TagPages;
	tags: Tags;
	translationJobs: TranslationJobs;
	translationVotes: TranslationVotes;
	users: Users;
	userSettings: UserSettings;
	verifications: Verifications;
}
