/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleSlugRouteImport } from './routes/$locale/$slug'
import { Route as ApiTranslationJobsRouteRouteImport } from './routes/api/translation-jobs/route'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthRequestRouteImport } from './routes/api/auth/request'
import { Route as ApiAuthVerifyRouteImport } from './routes/api/auth/verify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/$locale/',
  path: '/$locale/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSlugRoute = LocaleSlugRouteImport.update({
  id: '/$locale/$slug',
  path: '/$locale/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranslationJobsRouteRoute = ApiTranslationJobsRouteRouteImport.update({
  id: '/api/translation-jobs',
  path: '/api/translation-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRequestRoute = ApiAuthRequestRouteImport.update({
  id: '/api/auth/request',
  path: '/api/auth/request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthVerifyRoute = ApiAuthVerifyRouteImport.update({
  id: '/api/auth/verify',
  path: '/api/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/translation-jobs': typeof ApiTranslationJobsRouteRoute
  '/$locale/$slug': typeof LocaleSlugRoute
  '/$locale/': typeof LocaleIndexRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/request': typeof ApiAuthRequestRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/translation-jobs': typeof ApiTranslationJobsRouteRoute
  '/$locale/$slug': typeof LocaleSlugRoute
  '/$locale': typeof LocaleIndexRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/request': typeof ApiAuthRequestRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/translation-jobs': typeof ApiTranslationJobsRouteRoute
  '/$locale/$slug': typeof LocaleSlugRoute
  '/$locale/': typeof LocaleIndexRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/request': typeof ApiAuthRequestRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/translation-jobs'
    | '/$locale/$slug'
    | '/$locale/'
    | '/api/auth/logout'
    | '/api/auth/request'
    | '/api/auth/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/translation-jobs'
    | '/$locale/$slug'
    | '/$locale'
    | '/api/auth/logout'
    | '/api/auth/request'
    | '/api/auth/verify'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/translation-jobs'
    | '/$locale/$slug'
    | '/$locale/'
    | '/api/auth/logout'
    | '/api/auth/request'
    | '/api/auth/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiTranslationJobsRouteRoute: typeof ApiTranslationJobsRouteRoute
  LocaleSlugRoute: typeof LocaleSlugRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthRequestRoute: typeof ApiAuthRequestRoute
  ApiAuthVerifyRoute: typeof ApiAuthVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/$locale'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$slug': {
      id: '/$locale/$slug'
      path: '/$locale/$slug'
      fullPath: '/$locale/$slug'
      preLoaderRoute: typeof LocaleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/translation-jobs': {
      id: '/api/translation-jobs'
      path: '/api/translation-jobs'
      fullPath: '/api/translation-jobs'
      preLoaderRoute: typeof ApiTranslationJobsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/request': {
      id: '/api/auth/request'
      path: '/api/auth/request'
      fullPath: '/api/auth/request'
      preLoaderRoute: typeof ApiAuthRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/verify': {
      id: '/api/auth/verify'
      path: '/api/auth/verify'
      fullPath: '/api/auth/verify'
      preLoaderRoute: typeof ApiAuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiTranslationJobsRouteRoute: ApiTranslationJobsRouteRoute,
  LocaleSlugRoute: LocaleSlugRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthRequestRoute: ApiAuthRequestRoute,
  ApiAuthVerifyRoute: ApiAuthVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
