name: Auto Label Issue

on:
  issues:
    types: [opened, edited]

jobs:
  auto_label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Label issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: |
          if [[ $ISSUE_TITLE =~ ^(feat:|feature:) ]]; then
            LABEL="feature"
          elif [[ $ISSUE_TITLE =~ ^(fix:|bug:) ]]; then
            LABEL="bug"
          elif [[ $ISSUE_TITLE =~ ^(docs:|documentation:) ]]; then
            LABEL="documentation"
          elif [[ $ISSUE_TITLE =~ ^refactor: ]]; then
            LABEL="refactor"
          elif [[ $ISSUE_TITLE =~ ^chore: ]]; then
            LABEL="chore"
          fi
          
          if [ -n "$LABEL" ]; then
            if gh issue edit $ISSUE_NUMBER --add-label "$LABEL"; then
              echo "Successfully added label: $LABEL to issue #$ISSUE_NUMBER"
            else
              echo "Failed to add label: $LABEL to issue #$ISSUE_NUMBER"
              exit 1
            fi
          else
            echo "No specific label determined for issue #$ISSUE_NUMBER. Skipping label addition."
          fi