name: Auto Label Issue

on:
  issues:
    types: [opened, edited]

jobs:
  auto_label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Label issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: |
          if [[ $ISSUE_TITLE =~ ^feat:|^feature: ]]; then
            LABEL="feature"
          elif [[ $ISSUE_TITLE =~ ^fix:|^bug: ]]; then
            LABEL="bug"
          elif [[ $ISSUE_TITLE =~ ^docs:|^documentation: ]]; then
            LABEL="documentation"
          elif [[ $ISSUE_TITLE =~ ^refactor: ]]; then
            LABEL="refactor"
          elif [[ $ISSUE_TITLE =~ ^chore: ]]; then
            LABEL="chore"
          else
            LABEL="task"
          fi
          
          gh issue edit $ISSUE_NUMBER --add-label "$LABEL"