name: Type Check

on:
  pull_request:
    branches: [ main ]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Bun
      run: |
        curl -fsSL https://bun.sh/install | bash
        export BUN_INSTALL="$HOME/.bun"
        export PATH="$BUN_INSTALL/bin:$PATH"
    - name: Install dependencies
      working-directory: ./web
      run: bun install
    - name: Run typecheck
      working-directory: ./web
      run: bun run typecheck